spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  name: "Welcome to Unicobank QA loans APIs"
  contactDetails:
    name: "Mitali Bose - QA Lead"
    email: "mtali.b13@bank.com"
  onCallSupport:
    - (91) 4332-091234
    - (91) 4569-234102